version: "3.7"

services: 

  server:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/public_html:/public_html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/certbot/conf:/etc/nginx/ssl
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - identity-server
      - moneys-api

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email yanrus09@gmail.com --agree-tos --no-eff-email -d yaniddze.com
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/logs:/var/log/letsencrypt
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt

  rabbit:
    image: 'rabbitmq:3.6-management-alpine'
    restart: always
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"

  identity-server:
    build: ./IdentityServer/Server
    restart: always
    # ports: 
      # - "8081:80"
    depends_on:
      - identity-postgres
      - rabbit
    
  identity-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./VolumeData/IdentityServer:/var/lib/postgresql/data

  moneys-api:
    build: ./MoneyApi/Api
    restart: always
    # ports: 
      # - "8082:80"
    depends_on:
      - identity-server
      - rabbit
      - moneys-postgres

  moneys-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./VolumeData/Moneys:/var/lib/postgresql/data
