version: "3.7"

services: 

  rabbit:
    image: 'rabbitmq:3.6-management-alpine'
    restart: always
    ports:
      - "15672:15672"

  identity-server:
    build: ./IdentityServer/Server
    restart: always
    ports: 
      - "8081:80"
    depends_on:
      - identity-postgres
      - rabbit
    
  identity-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./VolumeData/IdentityServer:/var/lib/postgresql/data

  moneys-api:
    build: ./MoneyApi/Api
    restart: always
    ports: 
      - "8082:80"
    depends_on:
      - identity-server
      - rabbit